### ISSUE TITLE
Error en el script converison XML a Json

### ISSUE THREAD

**Issue by gedas07** [kralizeck/tvhstar-parche-epg#6]
Hola 
lanzo el script /o el parche y me sale esto de arriba , ademas en la carpeta tmp no hay ningun fichero con ese nombre que indica arriba

2 - Leyendo el fichero XML de movistar /tmp/guia.movistar-xml.xml !! ERROR !!
Error en la conversion de XML (movistar) a JSON (movistar)

Muchas gracias por la ayuda

**Comment by kralizeck** [comment]
¿No hay errores antes?

**Comment by gedas07** [comment]
Esto es lo que me sale cuando paso el parche

> olicitando la guía desde el 2019-02-18 al 2019-02-25...


Convirtiendo /home/cubie/guia/guia.xml a formato xml viejuno de exportación de movistar...

Error: Unencoded <
Line: 102389
Column: 198
Char: .
    at error (/home/gedas07/tvhstar/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/home/gedas07/tvhstar/node_modules/sax/lib/sax.js:693:7)
    at SAXParser.write (/home/gedas07/tvhstar/node_modules/sax/lib/sax.js:1096:13)
    at Parser.exports.Parser.Parser.parseString (/home/gedas07/tvhstar/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/home/gedas07/tvhstar/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/home/gedas07/tvhstar/node_modules/xml2js/lib/xml2js.js:540:19)
    at /home/gedas07/tvhstar/borra_duplis_y_corrige_fecha.js:74:3
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'export' of undefined
    at /home/gedas07/tvhstar/borra_duplis_y_corrige_fecha.js:77:22
    at Parser.<anonymous> (/home/gedas07/tvhstar/node_modules/xml2js/lib/xml2js.js:493:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onerror (/home/gedas07/tvhstar/node_modules/xml2js/lib/xml2js.js:311:26)
    at emit (/home/gedas07/tvhstar/node_modules/sax/lib/sax.js:640:35)
    at error (/home/gedas07/tvhstar/node_modules/sax/lib/sax.js:669:5)
    at strictFail (/home/gedas07/tvhstar/node_modules/sax/lib/sax.js:693:7)
    at SAXParser.write (/home/gedas07/tvhstar/node_modules/sax/lib/sax.js:1096:13)
    at Parser.exports.Parser.Parser.parseString (/home/gedas07/tvhstar/node_modules/xml2js/lib/xml2js.js:508:31)

> tvhstar@1.0.0 start /home/gedas07/tvhstar
> node build/server.js

--
Inicio del ciclo de consulta del EPG
---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- 
1 - Descarga del EPG XML Movistar
  => PORT http://comunicacion.movistarplus.es/guiaProgramacion/exportar
  => EPG 2019-02-18 -> 2019-02-24
1 - Descarga del EPG XML Movistar - OK
2 - Leyendo el fichero XML de movistar /tmp/guia.movistar-xml.xml
2 - Leyendo el fichero XML de movistar /tmp/guia.movistar-xml.xml !! ERROR !!
Error en la conversion de XML (movistar) a JSON (movistar)

>

**Comment by kralizeck** [comment]
Es el mismo error reportado por @Meiden-fc, seguimos en ese hilo.

Duplicado de #5 

Posible solución: https://github.com/kralizeck/tvhstar-parche-epg/issues/5#issuecomment-465014514
