### ISSUE TITLE
Error al pasar el parche otra vez

### ISSUE THREAD

**Issue by gedas07** [kralizeck/tvhstar-parche-epg#7]
Esta vez me sale esto 
Seguro que es una tonteria, perono se arreglarlo

Solicitando la guía desde el 2019-06-02 al 2019-06-08...

Convirtiendo /home/rock64/guia/guia.xml a formato xml viejuno de exportación de movistar...

events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'pase' of undefined
    at /home/rock64/tvhstar/borra_duplis_y_corrige_fecha.js:77:29
    at Parser.<anonymous> (/home/rock64/tvhstar/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/rock64/tvhstar/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/rock64/tvhstar/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/rock64/tvhstar/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/rock64/tvhstar/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/rock64/tvhstar/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/rock64/tvhstar/node_modules/xml2js/lib/parser.js:322:31)
>>>> ERROR NODE.JS <<<< al procesar /home/rock64/guia/guia.xml con node.js - exit code node: 1

Muchas gracias

**Comment by gedas07** [comment]
lo puedo cerrar , ya lo he arreglado , me lo he vuelto a bajar , configurar y funciona perfectamente
